name: Build & publish Caddy secure image
on:
  push: { branches: [ main ] }
  schedule:               # daily 02:00 UTC – adjust
    - cron:  '0 2 * * *'
  workflow_dispatch:

env:
  IMAGE: ghcr.io/nazgulcoder/caddy-secure

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { packages: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:latest
          platforms: linux/amd64,linux/arm64
          provenance: false   # keep digest stable when code didn’t change
          sbom: false         # SBOM would add a changing layer
