name: Cleanup Untagged Images
on:
  schedule:
    - cron: "0 1 1 * *"
  workflow_dispatch:

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          owner: nazgulcoder
          package-name: caddy-secure
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: true
          # Keep only 5 untagged images
          min-versions-to-keep: 5
