name: Tag Release
on:
  workflow_dispatch:
    inputs:
      sha256:
        description: 'SHA256 dell immagine da taggare'
        required: true
        type: string
      new_tag:
        description: 'Nuovo tag (es: v1.0.0)'
        required: true
        type: string

jobs:
  tag-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: nazgulcoder/caddy-secure
          target: sha256:${{ inputs.sha256 }}
          tags: ${{ inputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
